# User specific paths for data, etc
Paths:
  # Location of image data
  image_directory : '/Users/loganfrank/Desktop/code/mlcv-final-project/data/single_class/'

  # Location of saved network weights, optimizers, etc.
  network_directory : '/Users/loganfrank/Desktop/code/mlcv-final-project/data/networks/'

  # Location of parsed data such as dataframes, etc.
  data_directory : '/Users/loganfrank/Desktop/code/mlcv-final-project/data/parsed/'
  
  # Location of results such as confusion matrices, final val/test accuracies, etc.
  results_directory : '/Users/loganfrank/Desktop/code/mlcv-final-project/data/results/'

  
# Useful if multiple code files share variables
Variables: